### ISSUE TITLE
Permissions on Data

### ISSUE THREAD

**Issue by imadmoussa1** [holgi/fastapi-permissions#4]
I am new to fast API, and I searching to implement permissions on the data level. I was reading the documentation of fastapi-permissions but did find what I need.
Can we Implement permissions on data level? (example, I can give user A to see an item with id 1, and give the User B access to edit item with id:2 and 4)

Thank you.

**Comment by holgi** [comment]
Yes, this is possible with this library. You'll need your data model to store the applied permissions somehow, but that's up to you.

Back to your question:
Let's assume a user needs to be logged in to read any item that has the status "published" and the editor of an item can edit it.

So "User A" can read item 1, if the user is logged in and the item is published; and "User B" can only edit item 2 and 4, since she or he is the editor of that item:

```python
class User(BaseModel):
    name: str

    def principals(self):
        return [f"user:{self.name}"]


class Item(BaseModel):
    id: int
    status: str  # (one of "draft", "published")
    editor: str  # name of the user

    def __acl__(self):
        acl = [
            (Allow, f"user:{self.editor}", "view"),
            (Allow, f"user:{self.editor}", "edit")
            ]
        if self.status == "published":
            acl.append( (Allow, Authenticated, "view") )
        return acl
        
# ommitted setup code

user_A = User("A")
user_B = User("B")

# item 1: viewable by user A and B, editable by user A
item_1 = Item(id=1, status="published", editor="A") 

# item 2: viewable only by A, editable by user A
item_2 = Item(id=2, status="draft", editor="A")

# item 3: viewable by user A and B, editable by user B
item_3 = Item(id=3, status="published", editor="B")

# item 4: viewable only by B, editable by user b
item_4 = Item(id=4, status="draft", editor="B")
```

I hope that helps and was not too complicated ;-)

**Comment by holgi** [comment]
Or in a more abstract way: The model used to represent your data should have an `__acl__(self)` function that returns an access control list. Since the model instance has access to its data, it can return an adjusted access control list based on that data.

**Comment by imadmoussa1** [comment]
@holgi Thank you, I was doing the same logic, by adding editor and view user to my model. but instead of using the __acl__(self) I added a condition on the endpoint level.
I will replace this condition by __acl__  it's easier.
